name: kennyrowe
favicon: null
layout_spectrum: 0.43086346751078963
typography_spectrum: 0.25045213755220175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45602529239840806
  lightness: 0.9994948224630207
  saturation: 0.6471360917203128
  rhythmicContrast: 0.19825780927203596
purpose: []
